FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends docker-cli docker-compose \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir aiohttp==3.9.5

COPY deployer_service.py /app/deployer_service.py

CMD ["python", "/app/deployer_service.py"]
